version: '3'

# Separation of concerns
# Separation of lifecycles / lifecycle awareness
services:
  db:
    image: arangodb:3.9.2
    ports:
      - 8529:8529
#    build:
#      context: ./docker/database
    container_name: db
    environment:
      - ARANGO_ROOT_USER=root
      # Docker secrets
      # https://docs.docker.com/engine/swarm/secrets/
      - ARANGO_ROOT_PASSWORD=openSesame
    volumes:
      - ./docker/database/dump:/dump 
#    command: sh -c "sleep 10 && arangorestore --input-directory '/dump' --create-collection true --create-database true --overwrite true --server.endpoint 'tcp://db:8529' --server.username 'root' --server.password 'openSesame' --server.database 'dex'"
#    networks:
#      - common-net
    network_mode: host
  db_init:
    image: arangodb:3.9.2
    container_name: db_init
    volumes:
      - ./docker/database/dump:/dump
    command: sh -c "sleep 10 && arangorestore --server.endpoint 'tcp://localhost:8529' --input-directory '/dump' --create-collection true --create-database true --overwrite true --include-system-collections true --server.username 'root' --server.password 'openSesame' --server.database 'dex'"
    network_mode: host
    
#  app:
  # application.config/properties
#    build:
#      context: ./codex
#    container_name: app
#    depends_on:
#      - db_init
#    ports:
#      - "8080:8080"  
#    networks:
#      - common-net
#    restart: on-failure
#    network_mode: host
#networks:
#  common-net: {}
#  default:
          

