version: '2'

services:
  app:
    build:
      context: ./codex
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
          
  db:
    image: 'arangodb:3.9.2'
    container_name: db
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
    volumes:
      - ./dump:/dump
    command: sh -c "arangorestore --input-directory "/dump" --create-collection true --create-database true --overwrite true --server.username "root" --server.password "openSesame" --server.database "dex""
    expose:
      - "8529"
