FROM arangodb:latest
RUN apk --update --no-cache add curl
#RUN apk add curl
# ADD ./dump/ /dump/
#ADD entrypoint.sh /entrypoint.sh
# ADD arangod.conf /arangod.conf
# RUN chmod +x entrypoint.sh && /entrypoint.sh
# CMD ["/bin/sh", "/entrypoint.sh"]

